apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task
spec:
  params:
    - name: repository
      description: the git repo
    - name: branch
      description: the branch      
  workspaces:
  - name: code
    mountPath: /home/fabdev/code
  steps:
  - name: build-and-push-1
    image: calanais/warp
    command:
      - /bin/bash
    args:
      - -c
      - |
        set -ex
        chown -R fabdev code
        ls -lart /home/fabdev/code
        whoami
        id
    securityContext:
      runAsUser: 0
  - name: pre-build-check
    image: calanais/warp
    env:
      - name: HOME
        value: "/home/fabdev"
    command: ["/bin/bash"]
    args:
      - -c
      - |
        set -ex
        whoami
        id
        $(workspaces.code.path)/run.sh
    securityContext:
      runAsUser: 1000      